trigger:
- main

variables:
  imageName: "ecommerce-app"

pool:
  vmImage: 'local-pool'

steps:
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: 'acr-connection'

    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
