# Database Connection
spring.datasource.url=jdbc:postgresql://postgres-service:5432/ecommerce_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'create' forces a fresh start by dropping the old table (removes the Laptop)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Explicitly tell Hibernate to use the exact names we provide
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Database Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.hbm2ddl.import_files=import.sql

# Actuator & Monitoring
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,prometheus