spring.datasource.url=jdbc:postgresql://postgres-service:5432/ecommerce_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ADD THESE TWO LINES
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health