# Database Connection
spring.datasource.url=jdbc:postgresql://postgres-service:5432/ecommerce_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'create' will drop existing tables and recreate them, clearing old manual data
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Database Initialization (The 5-product seed)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.hbm2ddl.import_files=import.sql

# Actuator & Monitoring (For Prometheus/Grafana)
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,prometheus