apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alphadata/azure-ecommerce.git
    targetRevision: HEAD
    path: 01-platform-infra/clusters/local/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager