apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/imran-devsecops/azure-ecommerce.git
    targetRevision: main
    path: 03-ecommerce-app/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      