apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.15.0
      helm:
        valueFiles:
          - $values/01-platform-infra/infrastructure/harbor/values.yaml
    - repoURL: https://gitlab.com/imran-devsecops/azure-ecommerce.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor-system
  # TOP LEVEL SPEC
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data/auth
    - group: "apps"
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true