apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default 
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 22.1.0
    helm:
      values: |
        image:
          registry: core.harbor.domain
          repository: quay-proxy/keycloak/keycloak
          tag: latest

        postgresql:
          image:
            registry: core.harbor.domain
            repository: dockerhub/bitnami/postgresql
            tag: latest
      parameters:
        - name: auth.adminUser
          value: admin
        - name: auth.adminPassword
          value: admin123
        - name: proxy
          value: "edge"
        - name: service.type
          value: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
  syncOptions:
    - CreateNamespace=true