apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-config.yaml
  - harbor-app.yaml
  - postgres-app.yaml
  - redis-app.yaml
  - ecommerce-backend.yaml
  - vault.yaml
  - vault-addons.yaml
  