apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-config.yaml
  - harbor-app.yaml
  - postgres-app.yaml
  - redis-app.yaml
  - ecommerce-backend.yaml
  - vault.yaml
  - vault-addons.yaml
  - k8s/keycloak-sa.yaml
  - k8s/keycloak-cm.yaml
  - k8s/keycloak-deployment.yaml
  - k8s/keycloak-ingress.yaml 
  - k8s/keycloak-svc.yaml
  