apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.2.6

    helm:
      skipCrds: true
      values: |
        admissionController:
          replicas: 1

        cleanupController:
          enabled: true

        reportsController:
          enabled: true

        backgroundController:
          enabled: true

        cleanupJobs:
          admissionReports:
            image:
              registry: core.harbor.domain
              repository: ecommerce/bitnami/kubectl
              tag: latest
          clusterAdmissionReports:
            image:
              registry: core.harbor.domain
              repository: ecommerce/bitnami/kubectl
              tag: latest
          clusterEphemeralReports:
            image:
              registry: core.harbor.domain
              repository: ecommerce/bitnami/kubectl
              tag: latest
          ephemeralReports:
            image:
              registry: core.harbor.domain
              repository: ecommerce/bitnami/kubectl
              tag: latest
          updateRequests:
            image:
              registry: core.harbor.domain
              repository: ecommerce/bitnami/kubectl
              tag: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      