apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/imran-devsecops/azure-ecommerce.git
    targetRevision: HEAD
    path: 01-platform-infra/infrastructure/vault # Where your new files are

    helm:
      valuesFiles:
        - vault-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true