apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "keycloak-role"
        vault.hashicorp.com/agent-inject-secret-keycloak-admin: "secret/data/keycloak"
        vault.hashicorp.com/agent-inject-template-keycloak-admin: |
          {{- with secret "secret/data/keycloak" -}}
          export KEYCLOAK_ADMIN={{ .Data.data.KEYCLOAK_ADMIN }}
          export KEYCLOAK_ADMIN_PASSWORD={{ .Data.data.KEYCLOAK_ADMIN_PASSWORD }}
          {{- end }}
    spec:
      serviceAccountName: keycloak-sa
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.1.1
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "Loading Vault secrets..."
              . /vault/secrets/keycloak-admin

              echo "Starting Keycloak with Postgres"
              exec /opt/keycloak/bin/kc.sh start \
                --db=postgres \
                --db-url=jdbc:postgresql://postgres.keycloak.svc.cluster.local:5432/keycloak \
                --db-username=$KC_DB_USERNAME \
                --db-password=$KC_DB_PASSWORD \
                --http-enabled=true \
                --http-port=8080 \
                --hostname=keycloak.ecommerce.local \
                --hostname-strict=false
                --proxy=edge 
                

          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres.keycloak.svc.cluster.local:5432/keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
      