apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "keycloak-role"
        vault.hashicorp.com/agent-inject-secret-keycloak-admin: "secret/data/keycloak"
        vault.hashicorp.com/agent-inject-template-keycloak-admin: |
          {{- with secret "secret/data/keycloak" -}}
          export KEYCLOAK_ADMIN={{ .Data.data.KEYCLOAK_ADMIN }}
          export KEYCLOAK_ADMIN_PASSWORD={{ .Data.data.KEYCLOAK_ADMIN_PASSWORD }}
          {{- end }}
    spec:
      serviceAccountName: keycloak-sa

      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.1.1

        command: ["/bin/sh"]

        args:
          - -c
          - |
            echo "Loading Vault secrets..."
            . /vault/secrets/keycloak-admin

            echo "Admin User: $KEYCLOAK_ADMIN"
            exec /opt/keycloak/bin/kc.sh start-dev --http-port=8080
            

        ports:
        - containerPort: 8080

        volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets

      volumes:
      - name: vault-secrets
        emptyDir:
          medium: Memory