global:
  enabled: true

server:
  enabled: true

  image:
    repository: hashicorp/vault
    tag: "1.16.1"

  ui:
    enabled: true

  # 🔥 CRITICAL FIX
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: microk8s-hostpath   # <-- IMPORTANT (you are using microk8s)

  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }

      storage "file" {
        path = "/vault/data"
      }

      disable_mlock = true

  service:
    enabled: true
    type: ClusterIP
    port: 8200

injector:
  enabled: true