apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.0 # Use the latest stable version
    chart: vault
    helm:
      values: |
        server:
          dev:
            enabled: true  # Using 'dev' mode for easier setup on local k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true