apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: vault
spec:
  tls:
  - hosts:
    - vault.ecommerce.local
    secretName: vault-tls
  rules:
  - host: vault.ecommerce.local
    http:
      paths:  
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault
            port:
              number: 8200