# Add this section to your harbor/values.yaml
core:
  hostAliases:
    - ip: "10.152.183.88"
      hostnames:
        - "keycloak.ecommerce.local"


expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      # This secret name is what cert-manager will create
      secretName: harbor-tls-cert
  ingress:
    hosts:
      core: core.harbor.domain
    annotations:
      kubernetes.io/ingress.class: nginx
      # This tells cert-manager to use the issuer we defined
      cert-manager.io/cluster-issuer: self-signed-issuer
      # Ensure it doesn't redirect to HTTPS before the cert is ready
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

# Changed to https and the domain you added to /etc/hosts
externalURL: https://core.harbor.domain

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "microk8s-hostpath"
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      storageClass: "microk8s-hostpath"
      size: 2Gi
    jobservice:
      storageClass: "microk8s-hostpath"
      size: 1Gi
    database:
      storageClass: "microk8s-hostpath"
      size: 1Gi
    redis:
      storageClass: "microk8s-hostpath"
      size: 1Gi