expose:
  type: ingress
  tls:
    enabled: false # We will enable this once cert-manager is up in Phase 1.2
  ingress:
    hosts:
      core: harbor.local
    annotations:
      kubernetes.io/ingress.class: nginx

externalURL: http://harbor.local

# Harbor requires Persistence
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "microk8s-hostpath"
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      storageClass: "microk8s-hostpath"
      size: 2Gi
    jobservice:
      storageClass: "microk8s-hostpath"
      size: 1Gi
    database:
      storageClass: "microk8s-hostpath"
      size: 1Gi
    redis:
      storageClass: "microk8s-hostpath"
      size: 1Gi