apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-app-sa
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: backend
          image: core.harbor.domain/ecommerce/backend-app:v11
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
              value: "DEBUG"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_REDIS
              value: "DEBUG"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: REDIS_HOST
              value: "redis-infra-master.redis-system.svc.cluster.local"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/ecommerce_db"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "create"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password-secret
                  key: redis-password
          resources:
            requests:
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"