apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "ecommerce-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/ecommerce/db"
        vault.hashicorp.com/vault-addr: "http://vault.vault.svc:8200"
        vault.hashicorp.com/vault-skip-verify: "true"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/ecommerce/db" -}}
          SPRING_DATASOURCE_USERNAME={{ .Data.data.username }}
          SPRING_DATASOURCE_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: backend-app-sa
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: backend
          image: core.harbor.domain/ecommerce/backend-app:latest
          ports:
            - containerPort: 8080
          command: ["/bin/sh", "-c"]
          args:
            - |
              source /vault/secrets/db
              exec java -jar /app/app.jar
          env:
            - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
              value: "DEBUG"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_REDIS
              value: "DEBUG"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: REDIS_HOST
              value: "redis-infra-master.redis-system.svc.cluster.local"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/ecommerce"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password-secret
                  key: redis-password
          resources:
            requests:
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"