trigger:
- main

pool:
  name: local-pool

variables:
  imageNameBackend: backend
  imageNameFrontend: frontend
  acrName: acrecommerceprod123

steps:

- task: Docker@2
  displayName: Build and Push Backend
  inputs:
    command: buildAndPush
    repository: $(imageNameBackend)
    dockerfile: backend/Dockerfile
    containerRegistry: acr-docker-connection
    tags: |
      latest

- task: Docker@2
  displayName: Build and Push Frontend
  inputs:
    command: buildAndPush
    repository: $(imageNameFrontend)
    dockerfile: frontend/Dockerfile
    containerRegistry: acr-docker-connection
    tags: |
      latest